"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['timey.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': 'timey.icns',
    'argv_emulation': True,
    'plist': {
        'LSUIElement': True,
    },
    'includes': ['six', 'packaging', 'packaging.version',
             'packaging.specifiers', 'packaging.requirements'],
    'packages': ['rumps'],
    "resources": [
        'Ship_Brass_Bell-Mike_Koenig-1458750630.mp3',
        'statusItemIcon.png',
        'Icon-32.png',
        'timey.icns',
        'playback_play.png',
        'playback_stop.png'
    ]
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
